//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLite.Net.DateTimeOffset.PostBuild.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SQLite.Net.DateTimeOffset.PostBuild.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup of the assembly file &quot;{0}&quot; could not be created. Error: {1}.
        /// </summary>
        internal static string Error_CreateBackupFailed {
            get {
                return ResourceManager.GetString("Error_CreateBackupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load assembly from file &quot;{0}&quot;. Error: {1}.
        /// </summary>
        internal static string Error_LoadAssembly {
            get {
                return ResourceManager.GetString("Error_LoadAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve attribute SQLite.Column. Error:{0}.
        /// </summary>
        internal static string Error_ResolveColumnAttributeCtorMethodFailed {
            get {
                return ResourceManager.GetString("Error_ResolveColumnAttributeCtorMethodFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve method System.DateTimeObject.ParseExact(). Error:{0}.
        /// </summary>
        internal static string Error_ResolveDateTimeOffsetParseExactMethodFailed {
            get {
                return ResourceManager.GetString("Error_ResolveDateTimeOffsetParseExactMethodFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve method System.DateTimeObject.ToString(). Error:{0}.
        /// </summary>
        internal static string Error_ResolveDateTimeOffsetToStringMethodFailed {
            get {
                return ResourceManager.GetString("Error_ResolveDateTimeOffsetToStringMethodFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve attribute SQLite.Ignore. Error:{0}.
        /// </summary>
        internal static string Error_ResolveIgnoreAttributeCtorMethodFailed {
            get {
                return ResourceManager.GetString("Error_ResolveIgnoreAttributeCtorMethodFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve property System.Globalization.CultureInfo.InvariantCulture. Error:{0}.
        /// </summary>
        internal static string Error_ResolveInvariantCultureGetterMethodFailed {
            get {
                return ResourceManager.GetString("Error_ResolveInvariantCultureGetterMethodFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The [DateTimeOffsetSerialize] attribute may only be used on properties of type DateTimeOffset!.
        /// </summary>
        internal static string Error_WrongDataType {
            get {
                return ResourceManager.GetString("Error_WrongDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing property {0}: Injecting string property for DateTimeOffset serialization..
        /// </summary>
        internal static string Message_PropertyProcessing {
            get {
                return ResourceManager.GetString("Message_PropertyProcessing", resourceCulture);
            }
        }
    }
}
